# ASP.NET Core backend pipeline for EduSync Assessment
trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  azureAppName: 'backendapprani'

steps:
- task: UseDotNet@2
  inputs:
    version: '$(dotnetVersion)'
    includePreviewVersions: true
  displayName: Install .NET SDK

- task: NuGetToolInstaller@1
  displayName: Install NuGet Tools

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: Restore NuGet Packages

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Build Solution

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
  displayName: Run Tests

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: Publish Artifacts

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AzureConnection'
    appType: 'webApp'
    WebAppName: '$(azureAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true
    AdditionalArguments: '-retryAttempts:6 -retryInterval:10000'
    AppSettings: |
      -ASPNETCORE_ENVIRONMENT Production
      -ASPNETCORE_DETAILEDERRORS true
      -ConnectionStrings.DefaultConnection $(SqlConnectionString)
      -AzureBlobStorage.ConnectionString $(BlobStorageConnectionString)
  displayName: Deploy to Azure Web App 